terminal length 0|debug
show logging
show capwap client conf
show capwap client rcb
show pnpinfo
show pnp log
show ipv6 dhcp
show dtls connections
show dtls statistics
debug capwap client event|debug
debug capwap client info|debug
debug capwap client payload|debug
debug capwap client detail|debug
debug capwap client pmtu|debug
debug capwap client events|debug
debug dtls client events|debug
debug dtls client events detail|debug
debug traffic host filter UDP dst_port 5246 capture|debug
debug traffic wired filter UDP dst_port 5246 capture|debug
show ip int br
debug capwap client error|debug
debug dtls client error|debug
debug dtls client event|debug
terminal monitor|debug
show logging