show logging
show platform resources
show processes cpu platform | include wncd
show ap image summary
show logging | include AP_JOIN_DISJOIN
show ap uptime
show wireless stats ap history
show ap crash-file
dir all | include crash
show processes cpu platform sorted
show logging
show platform software object-manager chassis active F0 childless-delete-object
show platform software object-manager chassis active F0 pending-issue-update
show wireless stats ap mac {mac} discovery detailed
show wireless stats ap mac {mac} join detailed
show logging profile wireless start last 15 min filter mac {mac} to-file harddisk:AP_DISCONNECT_ALWAYS_ON_LOG_{event_ts}.log
show logging
show ap name {ap_name} config general
show ap name {ap_name} uptime